name: Main

on:
    push:
        tags:
            - "v1.*"

jobs:
    build:
        if: github.event.base_ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: denoland/setup-deno@v1
              with:
                deno-version: v1.x

            - run: npm install --ignore-scripts

            - run: deno task bundle

            - name: Publish to npm
              run: |
                npm config set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
                npm publish --ignore-scripts
                cd bundling/bundle
                npm publish --ignore-scripts
              env :
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  generate_release_notes: true
